version: 0.2

phases:
  pre_build:
   commands:
       - echo "creating /build folder"
       - mkdir -p ./build/
  build:
    commands:
        - echo "Copying the file"
        - cp index.html ./build/
artifacts:
   files:
      - build/**/*
      - appspec.yml
